### ISSUE TITLE
make binrpm-pkg creates a RHEL style RPM when on SLES

### ISSUE THREAD

**Issue by bsallen-argonne** [intel-gpu/intel-gpu-i915-backports#121]
Currently when you run `make binrpm-pkg` to build a binary RPM package on SLES 15 SP4 it creates a RPM in a RHEL style instead of expected SUSE style KMP based package.

If seems `CUSTOM_KERN_1_VER` is getting defined somewhere, when running `make binrpm-pkg` on SLES 15 SP4 resulting https://github.com/intel-gpu/intel-gpu-i915-backports/blob/backport/main/Makefile.backport#L426C35-L426C35 to cause a RHEL like RPM to be generated. 

Currently `backport-mkbinspec` is called with passing an empty argument to `-s`. 

```shell
/usr/src/intel-i915-dkms-1.23.6.24.230425.29/scripts/backport-mkbinspec -n intel-i915 -v 1.23.6.24.230425.29.5.14.21.150400.24.81 -r 1 -p opensource -k /lib/modules/5.14.21-150400.24.81-default -s "" "" > /usr/src/intel-i915-dkms-1.23.6.24.230425.29/intel-i915.spec
```

Testing with the following patch:
```patch
--- Makefile.backport.orig	2023-08-24 20:01:51.299504000 +0000
+++ Makefile.backport	2023-08-24 19:59:39.631562000 +0000
@@ -423,8 +423,8 @@
 SLES_OSV_NAME = $(shell cat $(KLIB_BUILD)/include/generated/autoconf.h | grep "CONFIG_SUSE_KERNEL " | cut -d " " -f 2 | cut -d "_" -f 2)
 ifeq ($(RHEL_OSV_NAME), RHEL)
 	OS_DISTRO_NAME := $(RHEL_OSV_NAME)
-else ifneq ($(CUSTOM_KERN_1_VER),)
-	OS_DISTRO_NAME := $(CUSTOM_KERN_1_VER)
+#else ifneq ($(CUSTOM_KERN_1_VER),)
+#	OS_DISTRO_NAME := $(CUSTOM_KERN_1_VER)
 else ifeq ($(SLES_OSV_NAME), SUSE)
 	OS_DISTRO_NAME := $(SLES_OSV_NAME)
 	I915_BIN_PKG_VERSION := $(I915_PKG_VERSION)
```

Causes the correct arguments to be passed to backport-mkbinspec like so:

```shell
/usr/src/intel-i915-dkms-1.23.6.24.230425.29/scripts/backport-mkbinspec -n intel-i915 -v 1.23.6.24.230425.29 -r 1 -p opensource -k /lib/modules/5.14.21-150400.24.81-default -s SUSE "" > /usr/src/intel-i915-dkms-1.23.6.24.230425.29/intel-i915.spec
```

**Comment by smuqthya** [comment]
This is fixed can be fixed with below change. We will add it as part of upcoming releases

diff --git a/Makefile.backport b/Makefile.backport
index f2a5fa63701e..75060e4b043c 100644
--- a/Makefile.backport
+++ b/Makefile.backport
@@ -427,7 +427,7 @@ RHEL_OSV_NAME = $(shell cat $(KLIB_BUILD)/include/generated/uapi/linux/version.h
 SLES_OSV_NAME = $(shell cat $(KLIB_BUILD)/include/generated/autoconf.h | grep "CONFIG_SUSE_KERNEL " | cut -d " " -f 2 | cut -d "_" -f 2)
 ifeq ($(RHEL_OSV_NAME), RHEL)
        OS_DISTRO_NAME := $(RHEL_OSV_NAME)
-else ifneq ($(CUSTOM_KERN_1_VER),)
+else ifneq ($(CUSTOM_KERN_1_VER),"")
        OS_DISTRO_NAME := $(CUSTOM_KERN_1_VER)
 else ifeq ($(SLES_OSV_NAME), SUSE)
        OS_DISTRO_NAME := $(SLES_OSV_NAME)
