### ISSUE TITLE
Question about feature/version detection

### ISSUE THREAD

**Issue by flumm** [intel-gpu/intel-gpu-i915-backports#203]
Hi,

sorry for the noise, but I have a question about the feature/version detection. (slightly related to #190 )

We (Proxmox VE) build our kernel on top of Ubuntu sources, but don't name the kernels like Ubuntu does. While generally compilation should work, some features are detected by using the Ubuntu version of the kernel header sources (e.g. by parsing the `CONFIG_VERSION_SIGNATURE` of the `autoconf.h`)

thus we still run into the error mentioned above, because the check 

```
if LINUX_VERSION_IS_GEQ(6,9,6) || \
        (LINUX_VERSION_IS_GEQ(6,8,0) && UBUNTU_BACKPORT_VERSION_IS_GEQ(43,43))
```

is not triggered (kernel 6.8, but with Ubuntus patches).

Is there any way we could tell our users to build the package so it will always use that codepath, without patching the Makefile/sources ?

We could of course maintain a fork of this repo with the necessary changes, but this seems overkill for such a small change.

Would you accept patches to include Proxmox OSV detection?

**Comment by smuqthya** [comment]
Hi @flumm, 

W.r.t the condition mentioned above which control below commit. 

/*
 * 8e21de5f99b2 drm/mst: Fix NULL pointer dereference at drm_dp_add_payload_part2
 */
#define BPM_DRM_DP_ADD_PAYLOAD_PART2_ARG_NOT_PRESENT

This commit is not part of current vanilla 6.8.x kernel. 
 but since this got backported to ubuntu kernel. we have put a control of ubuntu which can be identifiable and supported by this repo. 

There is no bypass mechanism for unsupported kernel. You can create your own fork if you want to maintain specific changes on top of current code. 

For the above case you can either comment out code related to macro in file backport-include/drm/drm_dp_mst_helper.h
or patch to undefine or comment out the macro in backport_macro.h.
